### PR TITLE
Update "grafana" job to 4.6.3

### PR DESCRIPTION
**Pull request by jochenehret**
* incorporate changes from upstream sample.ini
* add config properties for WebDAV external image storage

### CODE REVIEW

**Comment by jochenehret** [comment]
@vito : Can you please merge this PR and build a new BOSH release with Grafana 4.6.3?

Thanks and Best Regards,

  @philippthun and @jochenehret.

**Comment by keithkroeger** [comment]
Hello @vito, would it be possible to consider this PR to allow a later version of Grafana?
We'd like to be able to use features in later versions such as PostgreSQL.

**Comment by vito** [comment]
Sure, sorry for the delay

**Comment by keithkroeger** [comment]
Thank you, @vito .

Will this create a new release?

**Comment by keithkroeger** [comment]
Hi @vito 
It appears ship-it may have failed

**Pull request merged**
